name: Retail Checkout Service CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v*']
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - '.vscode/**'
      - '.devcontainer/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/retail-checkout-service

permissions:
  contents: read
  pull-requests: write
  security-events: write
  checks: write
  statuses: write
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run linting
        run: yarn lint

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate container build
        run: |
          # Test that the container builds successfully
          docker build -t retail-checkout-service:test .
          echo "✅ Container builds successfully"

      - name: Validate container health check
        run: |
          # Test container startup and shutdown
          echo "🧪 Testing container startup and shutdown..."
          docker run -d --name test-container retail-checkout-service:test
          sleep 10

          # Check if container is running
          if docker ps --filter "name=test-container" --filter "status=running" --quiet; then
            echo "✅ Container started successfully"
          else
            echo "❌ Container failed to start"
            docker logs test-container
            exit 1
          fi

          # Clean up
          docker stop test-container
          docker rm test-container
          echo "✅ Container health check works"

      - name: Security scan
        run: |
          # Basic security checks
          echo "🔍 Checking for common security issues..."

          # Check for hardcoded secrets (basic check)
          if grep -r "password\|secret\|key\|token" src/ --exclude="*.ts" --exclude="*.js" --exclude="*.json" 2>/dev/null; then
            echo "⚠️  Potential hardcoded secrets found"
          fi

          # Check yarn dependencies for vulnerabilities
          if yarn audit --level moderate; then
            echo "✅ No dependency vulnerabilities found"
          else
            echo "⚠️  Vulnerabilities found in dependencies"
          fi

          echo "✅ Basic security checks completed"

      - name: Validation Summary
        run: |
          echo "🎉 All validations passed!"
          echo "✅ Dependencies installed successfully"
          echo "✅ Node.js application builds successfully"
          echo "✅ Container builds successfully"
          echo "✅ Container health check works"
          echo "✅ Security checks completed"

  build-and-push:
    needs: [validate, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
